import PDFDocument from "pdfkit";
import { prisma } from "../../config/database";
import {
  ASSET_REPORT_DISPLAY_NAMES,
  ASSET_STATUS,
  type AssetReportType,
  isValidAssetReportType,
  isValidAssetType,
} from "../../constants/assets";
import { HttpReplyError } from "../../utils/httpReplyError";
import { normalizeMoneyAmount } from "../../utils/monetaryAmount";
import {
  drawFittedCellText,
  drawKeyValueBox,
  ensurePageSpace,
  getPdfLayout,
  tableColumns,
} from "../../services/template/pdfLayout";
import { assetsService, computeStraightLineDepreciation } from "./assetsService";

const PRIMARY = "#008b8b";

function d(v: { toString(): string } | number | null | undefined): number {
  if (v == null) return 0;
  return typeof v === "number" ? v : Number(v);
}

function fmt(n: number): string {
  return new Intl.NumberFormat("en-NG", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(n);
}

function dateIso(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export type AssetReportFilters = {
  startDate?: Date;
  endDate?: Date;
  assetType?: string;
};

async function loadAssets(userId: string, filters: AssetReportFilters) {
  if (filters.assetType && !isValidAssetType(filters.assetType)) {
    throw new HttpReplyError(400, "Invalid assetType filter");
  }
  return prisma.asset.findMany({
    where: {
      userId,
      ...(filters.assetType ? { assetType: filters.assetType } : {}),
      ...(filters.startDate || filters.endDate
        ? {
            purchaseDate: {
              ...(filters.startDate ? { gte: filters.startDate } : {}),
              ...(filters.endDate ? { lte: filters.endDate } : {}),
            },
          }
        : {}),
    },
    orderBy: [{ assetType: "asc" }, { assetCode: "asc" }],
  });
}

function renderTablePdf(opts: {
  title: string;
  subtitle?: string;
  columns: { key: string; width: number; fromRight?: boolean; amount?: boolean }[];
  rows: Record<string, string>[];
  summaryRows?: { label: string; value: string }[];
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const layout = getPdfLayout(doc);
    const { left, contentWidth } = layout;
    let y = 50;

    doc.fontSize(16).fillColor(PRIMARY).text(opts.title, left, y, {
      width: contentWidth,
    });
    y = doc.y + 8;
    if (opts.subtitle) {
      doc.fontSize(8).fillColor("#6c757d").text(opts.subtitle, left, y, {
        width: contentWidth,
      });
      y = doc.y + 12;
    }

    if (opts.summaryRows?.length) {
      y = drawKeyValueBox(doc, layout, y, opts.summaryRows);
      y += 14;
    }

    const cols = tableColumns(
      layout,
      6,
      opts.columns.map((c) => ({
        key: c.key,
        width: c.width,
        fromRight: c.fromRight,
      })),
    );
    const amountKeys = new Set(
      opts.columns.filter((c) => c.amount).map((c) => c.key),
    );

    const headerH = 18;
    const rowH = 16;
    y = ensurePageSpace(doc, y, headerH + rowH);
    doc.rect(left, y, contentWidth, headerH).fillAndStroke("#e6f7f7", PRIMARY);
    for (const [key, col] of Object.entries(cols)) {
      drawFittedCellText(doc, key, col.x, y + 5, col.w, {
        align: amountKeys.has(key) ? "right" : "left",
        fontSize: 6,
        font: "Helvetica-Bold",
        color: "#004d4d",
      });
    }
    y += headerH;

    if (opts.rows.length === 0) {
      doc
        .fontSize(8)
        .fillColor("#6c757d")
        .text("No records for the selected filters.", left, y + 8, {
          width: contentWidth,
        });
    } else {
      for (const row of opts.rows) {
        y = ensurePageSpace(doc, y, rowH);
        doc.rect(left, y, contentWidth, rowH).stroke("#e9ecef");
        for (const [key, col] of Object.entries(cols)) {
          drawFittedCellText(doc, row[key] ?? "—", col.x, y + 4, col.w, {
            align: amountKeys.has(key) ? "right" : "left",
            fontSize: 7,
            color: "#4a4a4a",
          });
        }
        y += rowH;
      }
    }

    y = ensurePageSpace(doc, y + 16, 24);
    doc
      .fontSize(7)
      .fillColor("#6c757d")
      .text(`Generated by Fileam · ${new Date().toISOString().slice(0, 10)}`, left, y, {
        width: contentWidth,
      });
    doc.end();
  });
}

export const assetReportsService = {
  async generatePdf(
    userId: string,
    reportType: string,
    filters: AssetReportFilters = {},
  ): Promise<{ buffer: Buffer; filename: string }> {
    if (!isValidAssetReportType(reportType)) {
      throw new HttpReplyError(
        400,
        `Invalid reportType. Allowed: ${Object.keys(ASSET_REPORT_DISPLAY_NAMES).join(", ")}`,
      );
    }
    const type = reportType as AssetReportType;
    const title = ASSET_REPORT_DISPLAY_NAMES[type];
    const filterBits = [
      filters.startDate ? `from ${dateIso(filters.startDate)}` : null,
      filters.endDate ? `to ${dateIso(filters.endDate)}` : null,
      filters.assetType ? `type ${filters.assetType}` : null,
    ].filter(Boolean);
    const subtitle =
      filterBits.length > 0
        ? `Filters: ${filterBits.join(" · ")}`
        : "All assets (no filters)";

    const slug = title.replace(/\s+/g, "-");
    const filename = `${slug}-${dateIso(new Date())}.pdf`;

    if (type === "CURRENT_ASSETS_STATEMENT") {
      const snap = await assetsService.getCurrentAssetsSnapshot(userId);
      const buffer = await renderTablePdf({
        title,
        subtitle,
        summaryRows: [
          { label: "Cash", value: fmt(snap.cash.total) },
          { label: "Bank balances", value: fmt(snap.bankBalances.total) },
          { label: "Inventory", value: fmt(snap.inventory.total) },
          {
            label: "Accounts receivable",
            value: fmt(snap.accountsReceivable.total),
          },
          {
            label: "Total current assets",
            value: fmt(snap.totalCurrentAssets),
          },
        ],
        columns: [
          { key: "Component", width: 140 },
          { key: "Detail", width: 160 },
          { key: "Amount", width: 100, fromRight: true, amount: true },
        ],
        rows: [
          ...snap.cash.items.map((i) => ({
            Component: "Cash",
            Detail: `${i.title} — ${i.subtitle}`,
            Amount: fmt(i.amount),
          })),
          ...snap.bankBalances.items.map((i) => ({
            Component: "Bank",
            Detail: `${i.bankName} (${i.accountNumber})`,
            Amount: fmt(i.amount),
          })),
          ...snap.inventory.items.map((i) => ({
            Component: "Inventory",
            Detail: i.stockName,
            Amount: fmt(i.amount),
          })),
          ...snap.accountsReceivable.items.map((i) => ({
            Component: "Receivable",
            Detail: `${i.invoiceNumber} — ${i.customerName ?? "—"} (${i.status})`,
            Amount: fmt(i.amount),
          })),
        ],
      });
      return { buffer, filename };
    }

    const assets = await loadAssets(userId, filters);
    const now = new Date();

    if (type === "ASSET_MOVEMENT_REPORT") {
      const history = await prisma.assetHistory.findMany({
        where: {
          userId,
          type: { in: ["ASSET_TRANSFER", "ASSET_DISPOSAL", "ASSET_ACQUIRED"] },
          ...(filters.startDate || filters.endDate
            ? {
                eventDate: {
                  ...(filters.startDate ? { gte: filters.startDate } : {}),
                  ...(filters.endDate ? { lte: filters.endDate } : {}),
                },
              }
            : {}),
          ...(filters.assetType
            ? { asset: { assetType: filters.assetType } }
            : {}),
        },
        include: {
          asset: { select: { assetCode: true, assetName: true, assetType: true } },
        },
        orderBy: [{ eventDate: "desc" }, { createdAt: "desc" }],
        take: 500,
      });
      const buffer = await renderTablePdf({
        title,
        subtitle,
        columns: [
          { key: "Date", width: 70 },
          { key: "Asset", width: 70 },
          { key: "Name", width: 100 },
          { key: "Type", width: 70 },
          { key: "Action", width: 90 },
        ],
        rows: history.map((h) => ({
          Date: dateIso(h.eventDate),
          Asset: h.asset.assetCode,
          Name: h.asset.assetName,
          Type: h.asset.assetType,
          Action: h.type,
        })),
      });
      return { buffer, filename };
    }

    const mapped = assets.map((a) => {
      const cost = d(a.purchaseCost);
      const dep = computeStraightLineDepreciation({
        purchaseCost: cost,
        purchaseDate: a.purchaseDate,
        usefulLife: a.usefulLife,
        residualValue: d(a.residualValue),
        asOf: now,
      });
      return { a, cost, dep };
    });

    const totalCost = mapped.reduce((s, x) => s + x.cost, 0);
    const totalBook = mapped.reduce((s, x) => s + x.dep.bookValue, 0);
    const totalAccum = mapped.reduce(
      (s, x) => s + x.dep.accumulatedDepreciation,
      0,
    );
    const totalAnnual = mapped.reduce(
      (s, x) => s + x.dep.annualDepreciation,
      0,
    );

    if (type === "DEPRECIATION_SCHEDULE") {
      const buffer = await renderTablePdf({
        title,
        subtitle,
        summaryRows: [
          { label: "Annual depreciation (total)", value: fmt(totalAnnual) },
          { label: "Accumulated depreciation", value: fmt(totalAccum) },
        ],
        columns: [
          { key: "Asset", width: 60 },
          { key: "Name", width: 90 },
          { key: "Life", width: 36 },
          { key: "Cost", width: 80, fromRight: true, amount: true },
          { key: "Annual", width: 80, fromRight: true, amount: true },
          { key: "Accum.", width: 80, fromRight: true, amount: true },
          { key: "NBV", width: 80, fromRight: true, amount: true },
        ],
        rows: mapped.map(({ a, cost, dep }) => ({
          Asset: a.assetCode,
          Name: a.assetName,
          Life: a.usefulLife != null ? String(a.usefulLife) : "—",
          Cost: fmt(cost),
          Annual: fmt(dep.annualDepreciation),
          "Accum.": fmt(dep.accumulatedDepreciation),
          NBV: fmt(dep.bookValue),
        })),
      });
      return { buffer, filename };
    }

    if (type === "TAX_IMPACT_REPORT") {
      const buffer = await renderTablePdf({
        title,
        subtitle,
        summaryRows: [
          {
            label: "Estimated capital allowance (annual)",
            value: fmt(totalAnnual),
          },
        ],
        columns: [
          { key: "Asset", width: 60 },
          { key: "Name", width: 110 },
          { key: "Rate %", width: 50, fromRight: true, amount: true },
          { key: "Tax deduction", width: 100, fromRight: true, amount: true },
          { key: "NBV", width: 90, fromRight: true, amount: true },
        ],
        rows: mapped.map(({ a, dep }) => ({
          Asset: a.assetCode,
          Name: a.assetName,
          "Rate %": fmt(dep.depreciationPercentage || 0),
          "Tax deduction": fmt(dep.annualDepreciation),
          NBV: fmt(dep.bookValue),
        })),
      });
      return { buffer, filename };
    }

    if (type === "ASSET_INTELLIGENCE_REPORT") {
      const byType = new Map<string, { count: number; cost: number; nbv: number }>();
      for (const { a, cost, dep } of mapped) {
        const cur = byType.get(a.assetType) ?? { count: 0, cost: 0, nbv: 0 };
        cur.count += 1;
        cur.cost += cost;
        cur.nbv += dep.bookValue;
        byType.set(a.assetType, cur);
      }
      const active = mapped.filter((x) => x.a.status === ASSET_STATUS.ACTIVE)
        .length;
      const pending = mapped.filter((x) => x.a.status === ASSET_STATUS.PENDING)
        .length;
      const awaiting = mapped.filter(
        (x) => x.a.status === ASSET_STATUS.AWAITING,
      ).length;
      const buffer = await renderTablePdf({
        title,
        subtitle,
        summaryRows: [
          { label: "Total assets", value: String(mapped.length) },
          { label: "Active assets", value: String(active) },
          { label: "Pending", value: String(pending) },
          { label: "Awaiting review", value: String(awaiting) },
          { label: "Total purchase cost", value: fmt(totalCost) },
          { label: "Total net book value", value: fmt(totalBook) },
        ],
        columns: [
          { key: "Asset type", width: 140 },
          { key: "Count", width: 50, fromRight: true, amount: true },
          { key: "Cost", width: 100, fromRight: true, amount: true },
          { key: "NBV", width: 100, fromRight: true, amount: true },
        ],
        rows: [...byType.entries()].map(([t, v]) => ({
          "Asset type": t,
          Count: String(v.count),
          Cost: fmt(normalizeMoneyAmount(v.cost)),
          NBV: fmt(normalizeMoneyAmount(v.nbv)),
        })),
      });
      return { buffer, filename };
    }

    // ASSET_SUMMARY_REPORT (default)
    const buffer = await renderTablePdf({
      title,
      subtitle,
      summaryRows: [
        { label: "Assets in report", value: String(mapped.length) },
        { label: "Purchase cost", value: fmt(totalCost) },
        { label: "Accumulated depreciation", value: fmt(totalAccum) },
        { label: "Net book value", value: fmt(totalBook) },
      ],
      columns: [
        { key: "Asset", width: 60 },
        { key: "Name", width: 100 },
        { key: "Type", width: 70 },
        { key: "Status", width: 50 },
        { key: "Cost", width: 80, fromRight: true, amount: true },
        { key: "NBV", width: 80, fromRight: true, amount: true },
      ],
      rows: mapped.map(({ a, cost, dep }) => ({
        Asset: a.assetCode,
        Name: a.assetName,
        Type: a.assetType,
        Status: a.status,
        Cost: fmt(cost),
        NBV: fmt(dep.bookValue),
      })),
    });
    return { buffer, filename };
  },
};
