export const LEDGER_REFERENCE_TYPES = {
  CASH_OPENING: "CASH_OPENING",
  BANK_OPENING: "BANK_OPENING",
  RECEIVABLE: "RECEIVABLE",
  REVERSAL: "REVERSAL",
} as const;

export const LEDGER_STATUS = {
  POSTED: "POSTED",
  REVERSED: "REVERSED",
} as const;

export const LEDGER_ACCOUNTS = {
  CASH_ON_HAND: "CASH_ON_HAND",
  PETTY_CASH: "PETTY_CASH",
  OTHER_CASH: "OTHER_CASH",
  BANK: "BANK",
  OWNER_CAPITAL: "OWNER_CAPITAL",
  LOAN_LIABILITY: "LOAN_LIABILITY",
  EXISTING_BUSINESS_FUNDS: "EXISTING_BUSINESS_FUNDS",
  TRANSFER_CLEARING: "TRANSFER_CLEARING",
  OTHER_EQUITY: "OTHER_EQUITY",
  ASSET_SALE_RECEIVABLE: "ASSET_SALE_RECEIVABLE",
  ASSET_SALE_PROCEEDS: "ASSET_SALE_PROCEEDS",
  VENDOR_REFUND_RECEIVABLE: "VENDOR_REFUND_RECEIVABLE",
  EMPLOYEE_ADVANCE_RECEIVABLE: "EMPLOYEE_ADVANCE_RECEIVABLE",
  TAX_REFUND_RECEIVABLE: "TAX_REFUND_RECEIVABLE",
  INVESTMENT_INCOME_RECEIVABLE: "INVESTMENT_INCOME_RECEIVABLE",
  INVESTMENT_INCOME: "INVESTMENT_INCOME",
} as const;

export type LedgerEntryDraft = {
  accountCode: string;
  accountName: string;
  debit: number;
  credit: number;
};
