/**
 * Chart of accounts and reference types for double-entry posting.
 * Matrix source: accounting transaction types spec (1.pdf).
 */

export const LEDGER_REFERENCE_TYPES = {
  CASH_OPENING: "CASH_OPENING",
  BANK_OPENING: "BANK_OPENING",
  RECEIVABLE: "RECEIVABLE",
  REVERSAL: "REVERSAL",
  /** Sales revenue recognition (cash or credit). */
  SALE_RECOGNITION: "SALE_RECOGNITION",
  /** Customer payment clearing AR (sales or payers). */
  SALE_COLLECTION: "SALE_COLLECTION",
  /** Expense recognition (paid or on credit). */
  EXPENSE_RECOGNITION: "EXPENSE_RECOGNITION",
  /** Supplier / AP payment. */
  EXPENSE_PAYMENT: "EXPENSE_PAYMENT",
  PAYER_RECOGNITION: "PAYER_RECOGNITION",
  PAYER_COLLECTION: "PAYER_COLLECTION",
  BENEFICIARY_INVOICE: "BENEFICIARY_INVOICE",
  BENEFICIARY_PAYMENT: "BENEFICIARY_PAYMENT",
  WHT_REMITTED: "WHT_REMITTED",
  LOAN_RECEIVED: "LOAN_RECEIVED",
  LOAN_PRINCIPAL_PAID: "LOAN_PRINCIPAL_PAID",
  LOAN_INTEREST_PAID: "LOAN_INTEREST_PAID",
  OWNER_CAPITAL: "OWNER_CAPITAL",
  OWNER_WITHDRAWAL: "OWNER_WITHDRAWAL",
  ASSET_PURCHASE: "ASSET_PURCHASE",
  DEPRECIATION: "DEPRECIATION",
  VAT_REMITTED: "VAT_REMITTED",
  WHT_SUFFERED: "WHT_SUFFERED",
  SALARY_ACCRUED: "SALARY_ACCRUED",
  SALARY_PAID: "SALARY_PAID",
  TAX_PAID: "TAX_PAID",
} as const;

export const LEDGER_STATUS = {
  POSTED: "POSTED",
  REVERSED: "REVERSED",
} as const;

export const LEDGER_ACCOUNTS = {
  CASH_ON_HAND: "CASH_ON_HAND",
  PETTY_CASH: "PETTY_CASH",
  OTHER_CASH: "OTHER_CASH",
  BANK: "BANK",
  /** Card processor settlement — mapped business account when card payments confirm. */
  CARD_SETTLEMENT: "CARD_SETTLEMENT",
  CUSTOMER_AR: "CUSTOMER_AR",
  SALES_REVENUE: "SALES_REVENUE",
  VAT_PAYABLE: "VAT_PAYABLE",
  EXPENSE: "EXPENSE",
  ACCOUNTS_PAYABLE: "ACCOUNTS_PAYABLE",
  LOAN_LIABILITY: "LOAN_LIABILITY",
  FINANCE_COST: "FINANCE_COST",
  OWNER_CAPITAL: "OWNER_CAPITAL",
  OWNER_DRAWINGS: "OWNER_DRAWINGS",
  FIXED_ASSET: "FIXED_ASSET",
  ACCUMULATED_DEPRECIATION: "ACCUMULATED_DEPRECIATION",
  DEPRECIATION_EXPENSE: "DEPRECIATION_EXPENSE",
  WHT_PAYABLE: "WHT_PAYABLE",
  WHT_TAX_CREDIT: "WHT_TAX_CREDIT",
  SALARY_EXPENSE: "SALARY_EXPENSE",
  SALARY_PAYABLE: "SALARY_PAYABLE",
  PAYE_PAYABLE: "PAYE_PAYABLE",
  PENSION_PAYABLE: "PENSION_PAYABLE",
  TAX_PAYABLE: "TAX_PAYABLE",
  EXISTING_BUSINESS_FUNDS: "EXISTING_BUSINESS_FUNDS",
  TRANSFER_CLEARING: "TRANSFER_CLEARING",
  OTHER_EQUITY: "OTHER_EQUITY",
  ASSET_SALE_RECEIVABLE: "ASSET_SALE_RECEIVABLE",
  ASSET_SALE_PROCEEDS: "ASSET_SALE_PROCEEDS",
  VENDOR_REFUND_RECEIVABLE: "VENDOR_REFUND_RECEIVABLE",
  EMPLOYEE_ADVANCE_RECEIVABLE: "EMPLOYEE_ADVANCE_RECEIVABLE",
  TAX_REFUND_RECEIVABLE: "TAX_REFUND_RECEIVABLE",
  INVESTMENT_INCOME_RECEIVABLE: "INVESTMENT_INCOME_RECEIVABLE",
  INVESTMENT_INCOME: "INVESTMENT_INCOME",
} as const;

export const LEDGER_ACCOUNT_NAMES: Record<string, string> = {
  [LEDGER_ACCOUNTS.CASH_ON_HAND]: "Cash",
  [LEDGER_ACCOUNTS.BANK]: "Bank",
  [LEDGER_ACCOUNTS.CARD_SETTLEMENT]: "Card Settlement",
  [LEDGER_ACCOUNTS.CUSTOMER_AR]: "Customer Accounts Receivable",
  [LEDGER_ACCOUNTS.SALES_REVENUE]: "Sales Revenue",
  [LEDGER_ACCOUNTS.VAT_PAYABLE]: "VAT Payable",
  [LEDGER_ACCOUNTS.EXPENSE]: "Expense",
  [LEDGER_ACCOUNTS.ACCOUNTS_PAYABLE]: "Accounts Payable",
  [LEDGER_ACCOUNTS.LOAN_LIABILITY]: "Loan Liability",
  [LEDGER_ACCOUNTS.FINANCE_COST]: "Finance Cost",
  [LEDGER_ACCOUNTS.OWNER_CAPITAL]: "Owner Capital",
  [LEDGER_ACCOUNTS.OWNER_DRAWINGS]: "Owner Drawings",
  [LEDGER_ACCOUNTS.FIXED_ASSET]: "Fixed Asset",
  [LEDGER_ACCOUNTS.ACCUMULATED_DEPRECIATION]: "Accumulated Depreciation",
  [LEDGER_ACCOUNTS.DEPRECIATION_EXPENSE]: "Depreciation Expense",
  [LEDGER_ACCOUNTS.WHT_PAYABLE]: "WHT Payable",
  [LEDGER_ACCOUNTS.WHT_TAX_CREDIT]: "WHT Tax Credit",
  [LEDGER_ACCOUNTS.SALARY_EXPENSE]: "Salary Expense",
  [LEDGER_ACCOUNTS.SALARY_PAYABLE]: "Salary Payable",
  [LEDGER_ACCOUNTS.PAYE_PAYABLE]: "PAYE Payable",
  [LEDGER_ACCOUNTS.PENSION_PAYABLE]: "Pension Payable",
  [LEDGER_ACCOUNTS.TAX_PAYABLE]: "Tax Payable",
};

export type LedgerEntryDraft = {
  accountCode: string;
  accountName: string;
  debit: number;
  credit: number;
};
