/**
 * PDF Templates - Email design pattern for professional transaction documents.
 * Consistent branding: Fileam logo, primary color, structured layout.
 */
import PDFDocument from "pdfkit";
import type { Decimal } from "@prisma/client/runtime/library";

const PRIMARY_COLOR = "#008b8b";
const DOMAIN = "https://fileam.app";

function toNum(d: Decimal | number | null | undefined): number {
  if (d == null) return 0;
  return typeof d === "number" ? d : Number(d);
}

function formatDate(d: Date): string {
  return new Date(d).toLocaleDateString("en-NG", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function formatCurrency(amount: number, currency = "NGN"): string {
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency,
    minimumFractionDigits: 2,
  }).format(amount);
}

export interface InvoiceData {
  invoiceNumber: string;
  customerName: string | null;
  description: string;
  amount: number;
  vatRate: number;
  vatAmount: number;
  totalAmount: number;
  paymentType: string;
  saleDate: Date;
  vatableIncome: boolean;
  serviceIncome: boolean;
  status: string;
  businessName?: string;
  businessAddress?: string;
}

export function generateInvoicePdf(data: InvoiceData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 100;
    const col1 = 50;
    const col2 = pageWidth / 2 + 25;

    doc
      .fontSize(24)
      .fillColor(PRIMARY_COLOR)
      .text("INVOICE", col1, 50, { width: pageWidth })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .fillColor("#6c757d")
      .text(`Invoice #${data.invoiceNumber}`, col1)
      .text(`Date: ${formatDate(data.saleDate)}`, col1)
      .text(`Status: ${data.status}`, col1)
      .moveDown(1);

    doc.fillColor("#1a1a1a").fontSize(11);
    if (data.businessName) {
      doc.text("From:", col1).fontSize(10).text(data.businessName, col1);
      if (data.businessAddress) doc.text(data.businessAddress, col1);
      doc.moveDown(1).fontSize(11);
    }

    doc.text("Bill To:", col1).fontSize(10);
    doc.text(data.customerName || "Customer", col1);
    doc.moveDown(1.5).fontSize(11);

    const tableTop = doc.y;
    doc
      .rect(col1, tableTop, pageWidth, 22)
      .fillAndStroke("#f8f9fa", PRIMARY_COLOR);
    doc
      .fillColor("#1a1a1a")
      .fontSize(10)
      .font("Helvetica-Bold")
      .text("Description", col1 + 10, tableTop + 6, { width: 200 })
      .text("Amount", col1 + 220, tableTop + 6, { width: 80 })
      .text("VAT", col1 + 300, tableTop + 6, { width: 80 })
      .text("Total", col1 + 380, tableTop + 6, { width: 90 })
      .font("Helvetica");

    doc
      .rect(col1, tableTop + 22, pageWidth, 28)
      .stroke(PRIMARY_COLOR);
    doc
      .fillColor("#4a4a4a")
      .fontSize(10)
      .text(data.description, col1 + 10, tableTop + 30, { width: 200 })
      .text(formatCurrency(data.amount), col1 + 220, tableTop + 30, { width: 80 })
      .text(
        `${data.vatRate}% - ${formatCurrency(data.vatAmount)}`,
        col1 + 300,
        tableTop + 30,
        { width: 80 },
      )
      .text(formatCurrency(data.totalAmount), col1 + 380, tableTop + 30, {
        width: 90,
      });

    doc.moveDown(2);
    const totalY = doc.y;
    doc
      .rect(col1, totalY, 250, 40)
      .fillAndStroke("#e6f7f7", PRIMARY_COLOR);
    doc
      .font("Helvetica-Bold")
      .fontSize(12)
      .fillColor("#004d4d")
      .text("Total Amount", col1 + 15, totalY + 8)
      .text(formatCurrency(data.totalAmount), col1 + 15, totalY + 26);
    doc.font("Helvetica").fillColor("#1a1a1a");

    doc
      .fontSize(9)
      .fillColor("#6c757d")
      .text(`Payment: ${data.paymentType}`, col1, totalY + 55)
      .text(
        data.vatableIncome ? "Vatable Income: Yes" : "Vatable Income: No",
        col1,
        totalY + 68,
      )
      .text(
        data.serviceIncome ? "Service Income: Yes" : "Service Income: No",
        col1,
        totalY + 81,
      );

    doc
      .moveDown(3)
      .fontSize(9)
      .fillColor("#6c757d")
      .text("Thank you for your business.", col1)
      .text(`Generated by Fileam · ${DOMAIN}`, col1);

    doc.end();
  });
}

export interface ReceiptData {
  expenseNumber: string;
  description: string;
  category: string;
  amount: number;
  vatInclusive: boolean;
  vatAmount: number | null;
  totalAmount: number;
  expenseDate: Date;
  businessName?: string;
}

export function generateReceiptPdf(data: ReceiptData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 100;
    const col1 = 50;

    doc
      .fontSize(24)
      .fillColor(PRIMARY_COLOR)
      .text("RECEIPT", col1, 50, { width: pageWidth })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .fillColor("#6c757d")
      .text(`Receipt #${data.expenseNumber}`, col1)
      .text(`Date: ${formatDate(data.expenseDate)}`, col1)
      .text(`Category: ${data.category}`, col1)
      .moveDown(1.5);

    doc.fillColor("#1a1a1a").fontSize(11);
    if (data.businessName) {
      doc.text("From:", col1).fontSize(10).text(data.businessName, col1);
      doc.moveDown(1).fontSize(11);
    }

    doc.fontSize(12).text("Description", col1).moveDown(0.3);
    doc
      .fontSize(11)
      .fillColor("#4a4a4a")
      .text(data.description, col1, doc.y, { width: pageWidth })
      .moveDown(1.5);

    doc
      .rect(col1, doc.y, pageWidth, 90)
      .fillAndStroke("#f8fafc", PRIMARY_COLOR);
    const boxTop = doc.y;
    doc
      .font("Helvetica-Bold")
      .fontSize(11)
      .fillColor("#1a1a1a")
      .text("Amount", col1 + 15, boxTop + 15)
      .text("VAT", col1 + 15, boxTop + 40)
      .text("Total", col1 + 15, boxTop + 65)
      .font("Helvetica");
    doc
      .fontSize(11)
      .fillColor("#4a4a4a")
      .text(
        formatCurrency(data.amount),
        col1 + 200,
        boxTop + 15,
        { width: 150, align: "right" },
      )
      .text(
        data.vatInclusive
          ? `Inclusive (${formatCurrency(data.vatAmount ?? 0)})`
          : "Exclusive",
        col1 + 200,
        boxTop + 40,
        { width: 150, align: "right" },
      )
      .text(formatCurrency(data.totalAmount), col1 + 200, boxTop + 65, {
        width: 150,
        align: "right",
      });

    doc
      .moveDown(2)
      .fontSize(9)
      .fillColor("#6c757d")
      .text("This is an official receipt for the transaction listed above.", col1)
      .text(`Generated by Fileam · ${DOMAIN}`, col1);

    doc.end();
  });
}

export interface TaxFilingData {
  taxType: string;
  periodYear: number;
  periodMonth: number;
  amountDue: number;
  penalties: number;
  totalPayable: number;
  filingDueDate: Date;
  status: string;
  currency: string;
  submittedAt: Date | null;
  stateOfOperation?: string | null;
  vatRegistrationNumber?: string | null;
}

export function generateTaxFilingPdf(data: TaxFilingData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 100;
    const col1 = 50;
    const periodLabel = `${new Date(data.periodYear, data.periodMonth - 1).toLocaleString("default", { month: "long" })} ${data.periodYear}`;

    doc
      .fontSize(24)
      .fillColor(PRIMARY_COLOR)
      .text(`${data.taxType} FILING`, col1, 50, { width: pageWidth })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .fillColor("#6c757d")
      .text(`Period: ${periodLabel}`, col1)
      .text(`Due Date: ${formatDate(data.filingDueDate)}`, col1)
      .text(`Status: ${data.status}`, col1);
    if (data.vatRegistrationNumber) {
      doc.text(`VAT Reg: ${data.vatRegistrationNumber}`, col1);
    }
    if (data.stateOfOperation) {
      doc.text(`State: ${data.stateOfOperation}`, col1);
    }
    doc.moveDown(1.5);

    doc
      .rect(col1, doc.y, pageWidth, 120)
      .fillAndStroke("#f8fafc", PRIMARY_COLOR);
    const boxTop = doc.y;
    doc
      .font("Helvetica-Bold")
      .fontSize(11)
      .fillColor("#1a1a1a")
      .text("Amount Due", col1 + 15, boxTop + 15)
      .text("Penalties", col1 + 15, boxTop + 45)
      .text("Total Payable", col1 + 15, boxTop + 75)
      .font("Helvetica");
    doc
      .fontSize(11)
      .fillColor("#4a4a4a")
      .text(
        formatCurrency(data.amountDue, data.currency),
        col1 + 250,
        boxTop + 15,
        { width: 150, align: "right" },
      )
      .text(
        formatCurrency(data.penalties, data.currency),
        col1 + 250,
        boxTop + 45,
        { width: 150, align: "right" },
      )
      .text(
        formatCurrency(data.totalPayable, data.currency),
        col1 + 250,
        boxTop + 75,
        { width: 150, align: "right" },
      );

    if (data.submittedAt) {
      doc
        .moveDown(1)
        .fontSize(9)
        .fillColor("#6c757d")
        .text(`Submitted: ${formatDate(data.submittedAt)}`, col1);
    }

    doc
      .moveDown(2)
      .fontSize(9)
      .fillColor("#6c757d")
      .text("Official tax filing document.", col1)
      .text(`Generated by Fileam · ${DOMAIN}`, col1);

    doc.end();
  });
}

export interface ReportData {
  reportType: string;
  periodLabel: string;
  periodYear: number;
  periodMonth: number;
  generatedAt: Date;
  format: string;
  status: string;
}

export function generateReportPdf(data: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 100;
    const col1 = 50;

    doc
      .fontSize(24)
      .fillColor(PRIMARY_COLOR)
      .text(data.reportType.toUpperCase(), col1, 50, { width: pageWidth })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .fillColor("#6c757d")
      .text(`Period: ${data.periodLabel}`, col1)
      .text(`Generated: ${formatDate(data.generatedAt)}`, col1)
      .text(`Format: ${data.format}`, col1)
      .text(`Status: ${data.status}`, col1)
      .moveDown(1.5);

    doc
      .rect(col1, doc.y, pageWidth, 60)
      .fillAndStroke("#e6f7f7", PRIMARY_COLOR);
    doc
      .fontSize(12)
      .fillColor("#004d4d")
      .text(
        `This report covers ${data.periodLabel} and was generated on ${formatDate(data.generatedAt)}.`,
        col1 + 15,
        doc.y + 20,
        { width: pageWidth - 30 },
      );

    doc
      .moveDown(2)
      .fontSize(9)
      .fillColor("#6c757d")
      .text("Official report document.", col1)
      .text(`Generated by Fileam · ${DOMAIN}`, col1);

    doc.end();
  });
}
