/**
 * PDF Templates - Email design pattern for professional transaction documents.
 * Consistent branding: Fileam logo, primary color, structured layout.
 */
import PDFDocument from "pdfkit";
import type { Decimal } from "@prisma/client/runtime/library";

const PRIMARY_COLOR = "#008b8b";
const DOMAIN = "https://fileam.app";

function toNum(d: Decimal | number | null | undefined): number {
  if (d == null) return 0;
  return typeof d === "number" ? d : Number(d);
}

function formatDate(d: Date): string {
  return new Date(d).toLocaleDateString("en-NG", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

/** Format amount with currency code (e.g. NGN 1,234,567.89). Uses code not symbol for PDF compatibility. */
function formatCurrency(amount: number, currency = "NGN"): string {
  const formatted = new Intl.NumberFormat("en-NG", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
    useGrouping: true,
  }).format(amount);
  return `${currency} ${formatted}`;
}

/** Alias for NGN amounts in reports. */
function formatNaira(amount: number): string {
  return formatCurrency(amount, "NGN");
}

export interface InvoiceData {
  invoiceNumber: string;
  customerName: string | null;
  description: string;
  amount: number;
  vatRate: number;
  vatAmount: number;
  totalAmount: number;
  paymentType: string;
  saleDate: Date;
  vatableIncome: boolean;
  serviceIncome: boolean;
  status: string;
  businessName?: string;
  businessAddress?: string;
}

export function generateInvoicePdf(data: InvoiceData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 100;
    const col1 = 50;
    const col2 = pageWidth / 2 + 25;

    doc
      .fontSize(22)
      .fillColor(PRIMARY_COLOR)
      .text("INVOICE", col1, 50, { width: pageWidth })
      .moveDown(0.5);

    doc
      .fontSize(8)
      .fillColor("#6c757d")
      .text(`Invoice #${data.invoiceNumber}`, col1)
      .text(`Date: ${formatDate(data.saleDate)}`, col1)
      .text(`Status: ${data.status}`, col1)
      .moveDown(1);

    doc.fillColor("#1a1a1a").fontSize(9);
    if (data.businessName) {
      doc.text("From:", col1).fontSize(8).text(data.businessName, col1);
      if (data.businessAddress) doc.text(data.businessAddress, col1);
      doc.moveDown(1).fontSize(9);
    }

    doc.text("Bill To:", col1).fontSize(8);
    doc.text(data.customerName || "Customer", col1);
    doc.moveDown(1.5).fontSize(9);

    const tableTop = doc.y;
    const rightEdge = col1 + pageWidth;
    const AMT_W = 115;
    const GAP = 10;
    const totalX = rightEdge - AMT_W;
    const vatX = totalX - GAP - AMT_W;
    const amountX = vatX - GAP - AMT_W;
    const descW = amountX - col1 - GAP - 10;
    doc
      .rect(col1, tableTop, pageWidth, 22)
      .fillAndStroke("#f8f9fa", PRIMARY_COLOR);
    doc
      .fillColor("#1a1a1a")
      .fontSize(8)
      .font("Helvetica-Bold")
      .text("Description", col1 + 10, tableTop + 6, { width: descW })
      .text("Amount", amountX, tableTop + 6, { width: AMT_W })
      .text("VAT", vatX, tableTop + 6, { width: AMT_W })
      .text("Total", totalX, tableTop + 6, { width: AMT_W })
      .font("Helvetica");

    doc
      .rect(col1, tableTop + 22, pageWidth, 28)
      .stroke(PRIMARY_COLOR);
    doc
      .fillColor("#4a4a4a")
      .fontSize(8)
      .text(data.description, col1 + 10, tableTop + 30, { width: descW })
      .text(formatCurrency(data.amount), amountX, tableTop + 30, { width: AMT_W })
      .text(
        `${data.vatRate}% - ${formatCurrency(data.vatAmount)}`,
        vatX,
        tableTop + 30,
        { width: AMT_W },
      )
      .text(formatCurrency(data.totalAmount), totalX, tableTop + 30, {
        width: AMT_W,
      });

    doc.moveDown(2);
    const totalY = doc.y;
    doc
      .rect(col1, totalY, 250, 40)
      .fillAndStroke("#e6f7f7", PRIMARY_COLOR);
    doc
      .font("Helvetica-Bold")
      .fontSize(10)
      .fillColor("#004d4d")
      .text("Total Amount", col1 + 15, totalY + 8)
      .text(formatCurrency(data.totalAmount), col1 + 15, totalY + 26);
    doc.font("Helvetica").fillColor("#1a1a1a");

    doc
      .fontSize(7)
      .fillColor("#6c757d")
      .text(`Payment: ${data.paymentType}`, col1, totalY + 55)
      .text(
        data.vatableIncome ? "Vatable Income: Yes" : "Vatable Income: No",
        col1,
        totalY + 68,
      )
      .text(
        data.serviceIncome ? "Service Income: Yes" : "Service Income: No",
        col1,
        totalY + 81,
      );

    doc
      .moveDown(3)
      .fontSize(7)
      .fillColor("#6c757d")
      .text("Thank you for your business.", col1)
      .text(`Generated by Fileam · ${DOMAIN}`, col1);

    doc.end();
  });
}

export interface ReceiptData {
  expenseNumber: string;
  description: string;
  category: string;
  amount: number;
  vatInclusive: boolean;
  vatAmount: number | null;
  totalAmount: number;
  expenseDate: Date;
  businessName?: string;
}

export function generateReceiptPdf(data: ReceiptData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 100;
    const col1 = 50;

    doc
      .fontSize(22)
      .fillColor(PRIMARY_COLOR)
      .text("RECEIPT", col1, 50, { width: pageWidth })
      .moveDown(0.5);

    doc
      .fontSize(8)
      .fillColor("#6c757d")
      .text(`Receipt #${data.expenseNumber}`, col1)
      .text(`Date: ${formatDate(data.expenseDate)}`, col1)
      .text(`Category: ${data.category}`, col1)
      .moveDown(1.5);

    doc.fillColor("#1a1a1a").fontSize(9);
    if (data.businessName) {
      doc.text("From:", col1).fontSize(8).text(data.businessName, col1);
      doc.moveDown(1).fontSize(9);
    }

    doc.fontSize(10).text("Description", col1).moveDown(0.3);
    doc
      .fontSize(9)
      .fillColor("#4a4a4a")
      .text(data.description, col1, doc.y, { width: pageWidth })
      .moveDown(1.5);

    doc
      .rect(col1, doc.y, pageWidth, 90)
      .fillAndStroke("#f8fafc", PRIMARY_COLOR);
    const boxTop = doc.y;
    doc
      .font("Helvetica-Bold")
      .fontSize(9)
      .fillColor("#1a1a1a")
      .text("Amount", col1 + 15, boxTop + 15)
      .text("VAT", col1 + 15, boxTop + 40)
      .text("Total", col1 + 15, boxTop + 65)
      .font("Helvetica");
    doc
      .fontSize(9)
      .fillColor("#4a4a4a")
      .text(
        formatCurrency(data.amount),
        col1 + 200,
        boxTop + 15,
        { width: 150 },
      )
      .text(
        data.vatInclusive
          ? `Inclusive (${formatCurrency(data.vatAmount ?? 0)})`
          : "Exclusive",
        col1 + 200,
        boxTop + 40,
        { width: 150 },
      )
      .text(formatCurrency(data.totalAmount), col1 + 200, boxTop + 65, {
        width: 150,
      });

    doc
      .moveDown(2)
      .fontSize(7)
      .fillColor("#6c757d")
      .text("This is an official receipt for the transaction listed above.", col1)
      .text(`Generated by Fileam · ${DOMAIN}`, col1);

    doc.end();
  });
}

export interface TaxFilingData {
  taxType: string;
  periodYear: number;
  periodMonth: number;
  amountDue: number;
  penalties: number;
  totalPayable: number;
  filingDueDate: Date;
  status: string;
  currency: string;
  submittedAt: Date | null;
  stateOfOperation?: string | null;
  vatRegistrationNumber?: string | null;
}

export function generateTaxFilingPdf(data: TaxFilingData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 100;
    const col1 = 50;
    const periodLabel = `${new Date(data.periodYear, data.periodMonth - 1).toLocaleString("default", { month: "long" })} ${data.periodYear}`;

    doc
      .fontSize(22)
      .fillColor(PRIMARY_COLOR)
      .text(`${data.taxType} FILING`, col1, 50, { width: pageWidth })
      .moveDown(0.5);

    doc
      .fontSize(8)
      .fillColor("#6c757d")
      .text(`Period: ${periodLabel}`, col1)
      .text(`Due Date: ${formatDate(data.filingDueDate)}`, col1)
      .text(`Status: ${data.status}`, col1);
    if (data.vatRegistrationNumber) {
      doc.text(`VAT Reg: ${data.vatRegistrationNumber}`, col1);
    }
    if (data.stateOfOperation) {
      doc.text(`State: ${data.stateOfOperation}`, col1);
    }
    doc.moveDown(1.5);

    doc
      .rect(col1, doc.y, pageWidth, 120)
      .fillAndStroke("#f8fafc", PRIMARY_COLOR);
    const boxTop = doc.y;
    doc
      .font("Helvetica-Bold")
      .fontSize(9)
      .fillColor("#1a1a1a")
      .text("Amount Due", col1 + 15, boxTop + 15)
      .text("Penalties", col1 + 15, boxTop + 45)
      .text("Total Payable", col1 + 15, boxTop + 75)
      .font("Helvetica");
    doc
      .fontSize(9)
      .fillColor("#4a4a4a")
      .text(
        formatCurrency(data.amountDue, data.currency),
        col1 + 250,
        boxTop + 15,
        { width: 150 },
      )
      .text(
        formatCurrency(data.penalties, data.currency),
        col1 + 250,
        boxTop + 45,
        { width: 150 },
      )
      .text(
        formatCurrency(data.totalPayable, data.currency),
        col1 + 250,
        boxTop + 75,
        { width: 150 },
      );

    if (data.submittedAt) {
      doc
        .moveDown(1)
        .fontSize(7)
        .fillColor("#6c757d")
        .text(`Submitted: ${formatDate(data.submittedAt)}`, col1);
    }

    doc
      .moveDown(2)
      .fontSize(7)
      .fillColor("#6c757d")
      .text("Official tax filing document.", col1)
      .text(`Generated by Fileam · ${DOMAIN}`, col1);

    doc.end();
  });
}

export interface ReportData {
  reportType: string;
  periodLabel: string;
  periodYear: number;
  periodMonth: number;
  generatedAt: Date;
  format: string;
  status: string;
}

export interface FullReportData extends ReportData {
  businessName?: string;
  businessAddress?: string;
  vatSummary: {
    outputVat: number;
    inputVatClaimable: number;
    netVatPayable: number;
    belowThreshold: boolean;
    vatThreshold: number;
    percentOfThreshold: number;
  };
  whtSummary: {
    serviceIncome: number;
    whtRate: number;
    estimatedWhtDeducted: number;
  };
  citSummary: {
    monthlyProfit: number;
    annualizedProfit: number;
    citRate: number;
    estimatedAnnualCit: number;
  };
  filings: Array<{
    taxType: string;
    periodLabel: string;
    amountDue: number;
    penalties: number;
    totalPayable: number;
    status: string;
    filingDueDate: Date;
  }>;
  sales: Array<{
    invoiceNumber: string;
    customerName: string | null;
    description: string;
    amount: number;
    vatAmount: number;
    totalAmount: number;
    saleDate: Date;
    status: string;
  }>;
  expenses: Array<{
    expenseNumber: string;
    description: string;
    category: string;
    amount: number;
    vatAmount: number;
    totalAmount: number;
    expenseDate: Date;
  }>;
  compliance: {
    totalFilings: number;
    submittedCount: number;
    pendingCount: number;
    overdueCount: number;
  };
}

/** Legacy minimal report PDF (kept for backward compatibility). */
export function generateReportPdf(data: ReportData): Promise<Buffer> {
  return generateFullReportPdf(
    { ...data, vatSummary: { outputVat: 0, inputVatClaimable: 0, netVatPayable: 0, belowThreshold: true, vatThreshold: 0, percentOfThreshold: 0 }, whtSummary: { serviceIncome: 0, whtRate: 0, estimatedWhtDeducted: 0 }, citSummary: { monthlyProfit: 0, annualizedProfit: 0, citRate: 0, estimatedAnnualCit: 0 }, filings: [], sales: [], expenses: [], compliance: { totalFilings: 0, submittedCount: 0, pendingCount: 0, overdueCount: 0 } },
    null,
  );
}

/** Full report PDF with VAT summary, financial records, logo, and professional design. */
export function generateFullReportPdf(
  data: FullReportData,
  logoBuffer: Buffer | null,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 100;
    const col1 = 50;
    const col2 = pageWidth / 2 + 25;
    const rightEdge = col1 + pageWidth;
    const AMT_W = 115; // Width for amount columns (NGN 12,345,678.90)
    const GAP = 8;
    let y = 50;

    // Header with logo
    if (logoBuffer) {
      try {
        doc.image(logoBuffer, col1, y, { width: 120, height: 40 });
      } catch {
        // Fallback if image fails
      }
      y += 50;
    } else {
      doc.fontSize(20).fillColor(PRIMARY_COLOR).text("FILEAM", col1, y);
      y += 35;
    }

    doc
      .fontSize(18)
      .fillColor(PRIMARY_COLOR)
      .text(data.reportType.toUpperCase(), col1, y, { width: pageWidth });
    y += 28;

    doc.fontSize(7).fillColor("#6c757d");
    doc.text(`Period: ${data.periodLabel}`, col1);
    doc.text(`Generated: ${formatDate(data.generatedAt)}`, col1);
    if (data.businessName) doc.text(`Business: ${data.businessName}`, col1);
    doc.text(`Format: ${data.format} | Status: ${data.status} | Currency: NGN`, col1);
    y = doc.y + 16;

    const drawSection = (title: string, content: () => void) => {
      if (doc.y > 700) {
        doc.addPage();
        y = 50;
      }
      doc
        .fontSize(9)
        .font("Helvetica-Bold")
        .fillColor(PRIMARY_COLOR)
        .text(title, col1)
        .moveDown(0.3)
        .font("Helvetica")
        .fillColor("#1a1a1a");
      content();
      doc.moveDown(0.8);
    };

    // VAT Return Summary
    drawSection("1. VAT RETURN SUMMARY", () => {
      doc
        .rect(col1, doc.y, pageWidth, 95)
        .fillAndStroke("#f8fafc", PRIMARY_COLOR);
      const boxTop = doc.y;
      doc.fontSize(7).fillColor("#4a4a4a");
      doc.text("Output VAT (Sales)", col1 + 12, boxTop + 12);
      doc.text(formatNaira(data.vatSummary.outputVat), rightEdge - AMT_W - 12, boxTop + 12, { width: AMT_W });
      doc.text("Input VAT (Purchases)", col1 + 12, boxTop + 28);
      doc.text(formatNaira(data.vatSummary.inputVatClaimable), rightEdge - AMT_W - 12, boxTop + 28, { width: AMT_W });
      doc.font("Helvetica-Bold").text("Net VAT Payable", col1 + 12, boxTop + 48);
      doc.text(formatNaira(data.vatSummary.netVatPayable), rightEdge - AMT_W - 12, boxTop + 48, { width: AMT_W });
      doc.font("Helvetica");
      doc.text(`Threshold: ${formatNaira(data.vatSummary.vatThreshold)} | ${data.vatSummary.percentOfThreshold.toFixed(1)}% of threshold`, col1 + 12, boxTop + 68);
      doc.text(data.vatSummary.belowThreshold ? "Below VAT registration threshold" : "Above VAT threshold", col1 + 12, boxTop + 82);
    });

    // WHT Schedule
    drawSection("2. WHT SCHEDULE", () => {
      doc
        .rect(col1, doc.y, pageWidth, 60)
        .fillAndStroke("#f8fafc", PRIMARY_COLOR);
      const boxTop = doc.y;
      doc.fontSize(7).fillColor("#4a4a4a");
      doc.text("Service Income", col1 + 12, boxTop + 12);
      doc.text(formatNaira(data.whtSummary.serviceIncome), rightEdge - AMT_W - 12, boxTop + 12, { width: AMT_W });
      doc.text(`WHT Rate: ${data.whtSummary.whtRate}%`, col1 + 12, boxTop + 28);
      doc.text("Estimated WHT Deducted", col1 + 12, boxTop + 44);
      doc.font("Helvetica-Bold").text(formatNaira(data.whtSummary.estimatedWhtDeducted), rightEdge - AMT_W - 12, boxTop + 44, { width: AMT_W });
      doc.font("Helvetica");
    });

    // CIT Summary
    drawSection("3. CIT SUMMARY", () => {
      doc
        .rect(col1, doc.y, pageWidth, 70)
        .fillAndStroke("#f8fafc", PRIMARY_COLOR);
      const boxTop = doc.y;
      doc.fontSize(7).fillColor("#4a4a4a");
      doc.text("Monthly Profit", col1 + 12, boxTop + 12);
      doc.text(formatNaira(data.citSummary.monthlyProfit), rightEdge - AMT_W - 12, boxTop + 12, { width: AMT_W });
      doc.text("Annualized Profit", col1 + 12, boxTop + 28);
      doc.text(formatNaira(data.citSummary.annualizedProfit), rightEdge - AMT_W - 12, boxTop + 28, { width: AMT_W });
      doc.text(`CIT Rate: ${data.citSummary.citRate}%`, col1 + 12, boxTop + 44);
      doc.text("Estimated Annual CIT", col1 + 12, boxTop + 58);
      doc.font("Helvetica-Bold").text(formatNaira(data.citSummary.estimatedAnnualCit), rightEdge - AMT_W - 12, boxTop + 58, { width: AMT_W });
      doc.font("Helvetica");
    });

    // Filing History
    drawSection("4. FILING HISTORY", () => {
      if (data.filings.length === 0) {
        doc.fontSize(7).fillColor("#6c757d").text("No filings for this period.", col1);
      } else {
        const tableTop = doc.y;
        const fTotalX = rightEdge - AMT_W;
        const fAmtDueX = fTotalX - GAP - AMT_W;
        const fStatusW = 72;
        const fStatusX = fAmtDueX - GAP - fStatusW;
        const fPeriodW = 72;
        const fPeriodX = col1 + 8 + 58 + GAP;
        const fTaxTypeX = col1 + 8;
        const fTaxTypeW = 58;
        doc.rect(col1, tableTop, pageWidth, 22).fillAndStroke("#e6f7f7", PRIMARY_COLOR);
        doc.fontSize(6).font("Helvetica-Bold").fillColor("#004d4d");
        doc.text("Tax Type", fTaxTypeX, tableTop + 6, { width: fTaxTypeW });
        doc.text("Period", fTaxTypeX + fTaxTypeW + GAP, tableTop + 6, { width: fPeriodW });
        doc.text("Status", fStatusX, tableTop + 6, { width: fStatusW });
        doc.text("Amount Due", fAmtDueX, tableTop + 6, { width: AMT_W });
        doc.text("Total", fTotalX, tableTop + 6, { width: AMT_W });
        doc.font("Helvetica").fillColor("#4a4a4a");
        let rowY = tableTop + 22;
        for (const f of data.filings) {
          if (rowY > 720) {
            doc.addPage();
            rowY = 50;
            doc.rect(col1, rowY - 22, pageWidth, 22).stroke(PRIMARY_COLOR);
          }
          doc.rect(col1, rowY, pageWidth, 18).stroke("#e9ecef");
          doc.text(f.taxType, fTaxTypeX, rowY + 4, { width: fTaxTypeW });
          doc.text(f.periodLabel, fTaxTypeX + fTaxTypeW + GAP, rowY + 4, { width: fPeriodW });
          doc.text(f.status, fStatusX, rowY + 4, { width: fStatusW });
          doc.text(formatNaira(f.amountDue), fAmtDueX, rowY + 4, { width: AMT_W });
          doc.text(formatNaira(f.totalPayable), fTotalX, rowY + 4, { width: AMT_W });
          rowY += 18;
        }
        doc.y = rowY + 4;
      }
    });

    // Sales (Financial Records)
    drawSection("5. SALES / INVOICES", () => {
      if (data.sales.length === 0) {
        doc.fontSize(7).fillColor("#6c757d").text("No sales for this period.", col1);
      } else {
        const tableTop = doc.y;
        const sTotalX = rightEdge - AMT_W;
        const sVatX = sTotalX - GAP - AMT_W;
        const sAmtX = sVatX - GAP - AMT_W;
        const sInvW = 70;
        const sCustW = sAmtX - col1 - 8 - GAP * 2 - sInvW;
        doc.rect(col1, tableTop, pageWidth, 20).fillAndStroke("#e6f7f7", PRIMARY_COLOR);
        doc.fontSize(6).font("Helvetica-Bold").fillColor("#004d4d");
        doc.text("Invoice", col1 + 8, tableTop + 5, { width: sInvW });
        doc.text("Customer", col1 + 8 + sInvW + GAP, tableTop + 5, { width: sCustW });
        doc.text("Amount", sAmtX, tableTop + 5, { width: AMT_W });
        doc.text("VAT", sVatX, tableTop + 5, { width: AMT_W });
        doc.text("Total", sTotalX, tableTop + 5, { width: AMT_W });
        doc.font("Helvetica").fillColor("#4a4a4a");
        let rowY = tableTop + 20;
        for (const s of data.sales) {
          if (rowY > 730) {
            doc.addPage();
            rowY = 50;
          }
          doc.rect(col1, rowY, pageWidth, 16).stroke("#e9ecef");
          doc.text(s.invoiceNumber, col1 + 8, rowY + 3, { width: sInvW });
          doc.text((s.customerName || "-").slice(0, 22), col1 + 8 + sInvW + GAP, rowY + 3, { width: sCustW });
          doc.text(formatNaira(s.amount), sAmtX, rowY + 3, { width: AMT_W });
          doc.text(formatNaira(s.vatAmount), sVatX, rowY + 3, { width: AMT_W });
          doc.text(formatNaira(s.totalAmount), sTotalX, rowY + 3, { width: AMT_W });
          rowY += 16;
        }
        doc.y = rowY + 4;
      }
    });

    // Expenses
    drawSection("6. EXPENSES", () => {
      if (data.expenses.length === 0) {
        doc.fontSize(7).fillColor("#6c757d").text("No expenses for this period.", col1);
      } else {
        const tableTop = doc.y;
        const eTotalX = rightEdge - AMT_W;
        const eVatX = eTotalX - GAP - AMT_W;
        const eAmtX = eVatX - GAP - AMT_W;
        const eReceiptW = 70;
        const eCatW = eAmtX - col1 - 8 - GAP * 2 - eReceiptW;
        doc.rect(col1, tableTop, pageWidth, 20).fillAndStroke("#e6f7f7", PRIMARY_COLOR);
        doc.fontSize(6).font("Helvetica-Bold").fillColor("#004d4d");
        doc.text("Receipt #", col1 + 8, tableTop + 5, { width: eReceiptW });
        doc.text("Category", col1 + 8 + eReceiptW + GAP, tableTop + 5, { width: eCatW });
        doc.text("Amount", eAmtX, tableTop + 5, { width: AMT_W });
        doc.text("VAT", eVatX, tableTop + 5, { width: AMT_W });
        doc.text("Total", eTotalX, tableTop + 5, { width: AMT_W });
        doc.font("Helvetica").fillColor("#4a4a4a");
        let rowY = tableTop + 20;
        for (const e of data.expenses) {
          if (rowY > 730) {
            doc.addPage();
            rowY = 50;
          }
          doc.rect(col1, rowY, pageWidth, 16).stroke("#e9ecef");
          doc.text(e.expenseNumber, col1 + 8, rowY + 3, { width: eReceiptW });
          doc.text(e.category.slice(0, 22), col1 + 8 + eReceiptW + GAP, rowY + 3, { width: eCatW });
          doc.text(formatNaira(e.amount), eAmtX, rowY + 3, { width: AMT_W });
          doc.text(formatNaira(e.vatAmount), eVatX, rowY + 3, { width: AMT_W });
          doc.text(formatNaira(e.totalAmount), eTotalX, rowY + 3, { width: AMT_W });
          rowY += 16;
        }
        doc.y = rowY + 4;
      }
    });

    // Compliance Summary
    drawSection("7. COMPLIANCE SUMMARY", () => {
      doc
        .rect(col1, doc.y, pageWidth, 70)
        .fillAndStroke("#f8fafc", PRIMARY_COLOR);
      const boxTop = doc.y;
      doc.fontSize(7).fillColor("#4a4a4a");
      doc.text("Total Filings", col1 + 12, boxTop + 12);
      doc.text(String(data.compliance.totalFilings), col2 + 80, boxTop + 12, { width: 120 });
      doc.text("Submitted/Paid", col1 + 12, boxTop + 28);
      doc.text(String(data.compliance.submittedCount), col2 + 80, boxTop + 28, { width: 120 });
      doc.text("Pending", col1 + 12, boxTop + 44);
      doc.text(String(data.compliance.pendingCount), col2 + 80, boxTop + 44, { width: 120 });
      doc.text("Overdue", col1 + 12, boxTop + 58);
      doc.text(String(data.compliance.overdueCount), col2 + 80, boxTop + 58, { width: 120 });
    });

    // Footer
    doc
      .moveDown(1.5)
      .fontSize(7)
      .fillColor("#6c757d")
      .text("Official report document. This report covers all VAT records, financial transactions, and filing status for the stated period.", col1, undefined, { width: pageWidth })
      .text(`Generated by Fileam · ${DOMAIN}`, col1);

    doc.end();
  });
}
