import express from "express";
import authRoutes from "./authRoutes";
import userRoutes from "./userRoutes";
import onboardingRoutes from "../../routes/onboardingRoutes";
import consultantRequestsRoutes from "./consultantRequestsRoutes";
import consultantDirectoryRoutes from "./consultantDirectoryRoutes";
import salesRoutes from "./salesRoutes";
import expensesRoutes from "./expensesRoutes";
import taxComputationRoutes from "./taxComputationRoutes";
import taxPayablesRoutes from "./taxPayablesRoutes";
import paymentRecordsRoutes from "./paymentRecordsRoutes";
import filingsRoutes from "./filingsRoutes";
import reportsRoutes from "./reportsRoutes";
import analyticsRoutes from "./analyticsRoutes";
import evidenceVaultRoutes from "./evidenceVaultRoutes";
import employeesRoutes from "./employeesRoutes";
import helpRoutes from "./helpRoutes";
import contactsAndTypesRoutes from "./contactsAndTypesRoutes";
import accountDeletionRoutes from "./accountDeletionRoutes";
import inventoryRoutes from "./inventoryRoutes";
import assetsRoutes from "./assetsRoutes";
import payrollRoutes from "./payrollRoutes";
import payeeRoutes from "./payeeRoutes";
import nhfRoutes from "./nhfRoutes";
import pensionRoutes from "./pensionRoutes";
import financialPositionRoutes from "./financialPositionRoutes";
import liabilityRoutes from "./liabilityRoutes";
import liabilitiesRoutes from "./liabilitiesRoutes";
import customersRoutes from "./customersRoutes";
import suppliersRoutes from "./suppliersRoutes";
import prepaymentsRoutes from "./prepaymentsRoutes";

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/user", userRoutes);
router.use("/onboarding", onboardingRoutes);
router.use("/consultant-requests", consultantRequestsRoutes);
router.use("/consultants", consultantDirectoryRoutes);
router.use("/sales", salesRoutes);
router.use("/expenses", expensesRoutes);
router.use("/tax-computation", taxComputationRoutes);
router.use("/tax-payables", taxPayablesRoutes);
router.use("/payments", paymentRecordsRoutes);
router.use("/filings", filingsRoutes);
router.use("/reports", reportsRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/evidence-vault", evidenceVaultRoutes);
router.use("/employees", employeesRoutes);
router.use("/payroll", payrollRoutes);
router.use("/payee", payeeRoutes);
router.use("/nhf", nhfRoutes);
router.use("/pension", pensionRoutes);
router.use("/help", helpRoutes);
router.use("/account-deletion", accountDeletionRoutes);
router.use("/contacts-and-types", contactsAndTypesRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/assets", assetsRoutes);
router.use("/financial-position", financialPositionRoutes);
router.use("/liability", liabilityRoutes);
router.use("/liabilities", liabilitiesRoutes);
router.use("/customers", customersRoutes);
router.use("/suppliers", suppliersRoutes);
router.use("/prepayments", prepaymentsRoutes);

export default router;

